### ISSUE TITLE
create building ontology

### ISSUE THREAD

**Issue by k00ni** [AKSW/leds-asp-f-ontologies#3]

**Comment by fkoestner** [comment]
made a first version of the building ontology. tried to keep it simple and more structural orientated. insert no navigational information. 
if navigational informantion are needed it muss be added by a different layer that musst be mapped onto the structure.
searched for more literature and previous works. there are some excellent works but mostly navigational orientated. so i decided to make a new one.

**Comment by k00ni** [comment]
Is it possible to post some of the work you mentioned, if it doesn't consume too much time of yours? Might worth reading it.

**Comment by fkoestner** [comment]
Okay sure. I haven't saved everything I read but I saved some of them.

M. Goetz, A. Zipf:
Extending OpenStreetMap to Indoor Environments: Bringing Volunteered Geographic Information to the Next Level

Xin Wang, Jianga Shang, Fangwen Yu and Jinjin Yan:
Indoor Semantic Location Models for Location-Based Services

Christos Anagnostopoulos, Vassileios Tsetsos, Panayotis Kikiras, Stathes P. Hadjiefthymiades:
OntoNav: A Semantic Indoor Navigation System

Patrick M. Dudas, Mahsa Ghafourian, Hassan A. Karimi:
ONALIN: Ontology and Algorithm for Indoor Routing

G. Brown, C. Nagel, Dr. S. Zlatanova, Prof. T. Kolbe:
Modelling 3D Topographic Space Against Indoor Navigation Requirements

Johannes Scholz, Stefan Schabus:
An Indoor Navigation Ontology for Production Assets in a Production Environment

There are a few more often mentioned ontologies/ideas:
- OntoNav
- INO (indoor naviagation ontology)
- 3DBO (from Goetz & Zipf) 

None of them was found in an implemented form. And the found documents coundn't fully convince me to use them as they are descriped. They tend to need more information than famos data actually contains.

**Comment by k00ni** [comment]
Current version reduced and stripped from accessibility related information (moved to a separate ontology).
