### ISSUE TITLE
more organized repository structure

### ISSUE THREAD

**Issue by fkoestner** [AKSW/leds-asp-f-ontologies#7]
i uploaded a few files but it feels a bit uncomfortable putting them into the root folder. Therefor i suggest using a new filestructure for better file organization.

possible structure:
/
-- ontologies/
-- -- visualisations/
-- -- todo/ (directory for descriptions of planned ontologies that have not been realized yet)

**Comment by k00ni** [comment]
Sure, don't hesitate to do that :+1: 

What is `ontologies/visualizations` for?

**Comment by k00ni** [comment]
I started to reorganize the repo in my way and hope you find it useful too.

I would do the following structure:
- ontologies
  - building/
    - README.md
    - illustration.png
    - ontology.ttl
  - elevator/
    - ...

That way, you have always straight paths, such as `ontologies/elevator/ontology.ttl`.

What do you think?

(**UPDATE**: info.txt => README.md)

**Comment by fkoestner** [comment]
Your new structure seems to be good.

Visualisation was ment to be a more visual apealing form of the ontology for most easy and fast understanding of the created ontology. Something like a picture of the ontology Tbox graph. It's not needed but I think it's nice for understanding the structure of an ontology.
