### ISSUE TITLE
Integrate unit ontology to outline width, height and depth values

### ISSUE THREAD

**Issue by k00ni** [AKSW/leds-asp-f-ontologies#8]
Relevant paper:
- http://www.semantic-web-journal.net/sites/default/files/swj177_7.pdf
- http://ncor.buffalo.edu/images/OBI_Image_Measurements.pdf (page 9)

Because we need to outline width, height and depth, we should do it a well defined way. The unit ontology for instance uses a blank node which represents the value. On it they attach a relation to the real value and another one to the measure unit (e.g. centimeter).

**Comment by k00ni** [comment]
First approach: https://github.com/AKSW/leds-asp-f-ontologies/tree/master/ontologies/unit

**Comment by fkoestner** [comment]
After we decided that the current unit ontology was not what we needed, I made a new concept. It's just a first try and I will think about simpler ways to achieve what we actually need.
The main idea behind that first draft is, that every unit exists as archetype. the user creates a new unit individual that has two properties.:
1 has_archetype to reference a archetype
2. raised_to_the_power
The IRI of the unit individual is also used as dataproperty that specifies the quantity of an object with the definied unit.

for further illustration:
- https://github.com/AKSW/leds-asp-f-ontologies/blob/master/ontologies/unit/showcase.png
- https://github.com/AKSW/leds-asp-f-ontologies/blob/master/ontologies/unit/structure.png

**Comment by fkoestner** [comment]
Found Units of Measurement Ontology, see link, that contains a list with lots of units. Also a list of prefixes for units is contained. This ontology could be used instead of an own one. Does not contains properties but this shouldn't make problems with an additional mini ontology specifying them.
- https://bioportal.bioontology.org/ontologies/UO

**Comment by k00ni** [comment]
Can you please provide a small example how to outline, for instance, the width of a door?

**Comment by fkoestner** [comment]
~~I'll do so, as soon as I have created and uploaded the (for now) last version. This should take less than an hour.~~
Okay before creating something new, I checked again whats around. I found:
- qudt: https://github.com/qudt/qudt-public-repo

I'll still make my own version. that uses the Units of Measurement Ontology. We can decide afterwards, what ontology meets our needs best.

**Comment by k00ni** [comment]
Sounds promising, will look into it next week.

**Comment by k00ni** [comment]
I checked the references in your last mail. These ontologies are very hard to understand and don't seem to fit in our case. One reason is, that it should be easy to use and adapt. Furthermore, i require that one is be able to understand an ontology in a couple of minutes. Our approach should be to collect/develop straight forward ontologies with a focus on easy usage and a low barrier to understand.

Given the following example:

```
:quantity a owl:Class .

:unit rdf:type owl:ObjectProperty ;
      rdfs:domain :quantity ;
      rdfs:range unit:0000000 .

ex:bed          measurement:length      _:anon1 .

_:anon1 a               quantity:quantity ;
                quantity:unit   unit:0000008 .
```

It seems very complex and not very intuitive. The authors of the ontology may had more in mind in comparison to what we want to use it for. That's fine, but in our scenario with a broader spectrum of people participating (technical-oriented, domain experts, some ontologists), we need knowledge modules which are more lightweight and easier to use.

**QUDT** is way more complex than **Units of measurement**. Given the following [illustration](http://www.qudt.org/images/QUDT-MainSystemDiagram1.jpg) and basic study of [qudt.org](http://qudt.org/), i still have no idea what is about. So its not suitable too.

**Therefore:** We should go back to my first approach, fix known problems and use it for now.

**Comment by fkoestner** [comment]
I agree. I made two new ones. One that is minimalistic and very easy to use and one that adopts some of the qualities of our first approach but, so I hope, more understandable and usable. Will make a visualision and add annotations before uploading them.

**Comment by k00ni** [comment]
In our last discussion we decided to use the minimalistic approach. So, this issue can be closed, right?
