### ISSUE TITLE
translation of definitions - barrier

### ISSUE THREAD

**Issue by fkoestner** [AKSW/leds-asp-f-ontologies#9]
I translated the terms we discussed yesterday. While translating I noticed that we still use the term barrier but we didn't define it.

suggestion:
barriere is a mostly impermeable structure that is preventing something from passing without separating a pyhsical room in multiple pyhsical rooms.

**Comment by k00ni** [comment]
A small adaption only:

> A barrier is a mostly impermeable structure which is preventing ~~something~~ someone from passing, without separating a physical room in multiple physical rooms.

I will add this to our general terms list. Please adapt if necessary.

**Comment by fkoestner** [comment]
okay. i agree it's someone not something.
